#!/bin/bash
set -e

# Copied from build_all/rebuild_all.

FWPATH="./"
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
GIT_COMMIT="$(git describe --dirty=* --tags)"

#################### HW a50s_v23c_12s ########################

COPYDIR=a50s_v23c_12s
rm -rf $COPYDIR
mkdir $COPYDIR

if true; then
# default
cd $FWPATH
touch conf_general.h
make -j8 build_args="-DHW_SOURCE=\\\"hw_a50s_v23c_core.c\\\" -DHW_HEADER=\\\"hw_a50s_v23c_12s.h\\\" -DGIT_COMMIT=\\\"${GIT_COMMIT}\\\"" USE_VERBOSE_COMPILE=no
cd $DIR
cp $FWPATH/build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default.bin
fi

if true; then
# default with HW limits disables
cd $FWPATH
touch conf_general.h
make -j8 build_args="-DDISABLE_HW_LIMITS -DHW_SOURCE=\\\"hw_a50s_v23c_core.c\\\" -DHW_HEADER=\\\"hw_a50s_v23c_12s.h\\\" -DGIT_COMMIT=\\\"${GIT_COMMIT}\\\"" USE_VERBOSE_COMPILE=no
cd $DIR
cp $FWPATH/build/BLDC_4_ChibiOS.bin $COPYDIR/VESC_default_no_hw_limits.bin
fi
